name: Typescript - compile code
on:
  push:
    branches:
      - "develop"
      - "v2.[5-9].x-release"
      - "v[3-9].*.x-release"
    paths:
      - "bigbluebutton-html5/**.ts"
      - "bigbluebutton-html5/**.tsx"
      - "bigbluebutton-html5/package.json"
      - "bigbluebutton-html5/package-lock.json"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "bigbluebutton-html5/**.ts"
      - "bigbluebutton-html5/**.tsx"
      - "bigbluebutton-html5/package.json"
      - "bigbluebutton-html5/package-lock.json"
permissions:
  contents: read
jobs:
  ts-code-compilation:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout PR's source merged into its target branch
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - name: Checkout commit/branch
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: run npm ci
        working-directory: bigbluebutton-html5
        run: npm ci
      - name: typescript code compilation
        working-directory: bigbluebutton-html5
        run: npx tsc
